name: Lint

on: workflow_call

jobs:
    lint:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: NX Set SHA
              uses: nrwl/nx-set-shas@v3

            - name: Setup Node.js
              uses: actions/setup-node@v3
              with:
                  cache: npm
                  node-version: 16

            - name: Install Dependencies
              run: npm ci

            - name: Lint
              run: npx nx affected --target=lint --parallel=3 --all --quiet
